### ISSUE TITLE
How to run backend-foler rest-api after closed terminal?

### ISSUE THREAD

**Issue by LonieN** [mhhrakib/emr#2]
Hi mr. MHR.
Can you help me how to run background backend-foler when terminal closed? 
App rest-api only can run when I reopen terminal and run `node app.js`

And a short time after terminal closed, when I open it and run cmd node app.js, console output error like:
    Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/test/hyperledger/fabric-samples/emr/rest_api/node_modules/express/lib/application.js:618:24)
    at init (/home/test/hyperledger/fabric-samples/emr/rest_api/backend-admin/app.js:23:9)

I have to run cmd: `sudo lsof -i :3001 \ kill PID` and rerun app.js after that it's ok.
I don't know what happen and how to fix it?

Thanks & Rgds.

**Comment by mhhrakib** [comment]
I am afraid that this may not be possible since you have to keep the node server up and running to listen for request on the specified port. If you're closing the terminal then you're terminating the server but the port may still remain open so you have to close that too before a rerun.
